from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.core.settings import settings


class ReportArtifactService:
    def __init__(self) -> None:
        self._output_dir = Path(settings.report_output_dir)
        self._output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, *, report_id: str, trip_id: str, report_type: str, format: str, payload: dict) -> tuple[str, str]:
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        stem = f"trip_{trip_id}_{report_type}_{report_id[:8]}_{timestamp}"

        if format == "json":
            file_path = self._output_dir / f"{stem}.json"
            self._write_json(file_path=file_path, payload=payload)
        elif format == "excel":
            file_path = self._output_dir / f"{stem}.xlsx"
            self._write_excel(file_path=file_path, payload=payload)
        elif format == "pdf":
            file_path = self._output_dir / f"{stem}.pdf"
            self._write_pdf(file_path=file_path, payload=payload)
        else:
            raise ValueError("unsupported report format")

        file_url = f"{settings.app_base_url}/api/v1/reports/files/{file_path.name}"
        return str(file_path), file_url

    def _write_json(self, *, file_path: Path, payload: dict) -> None:
        file_path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")

    def _write_excel(self, *, file_path: Path, payload: dict) -> None:
        from openpyxl import Workbook
        from openpyxl.styles import Font

        workbook = Workbook()
        summary_sheet = workbook.active
        summary_sheet.title = "Summary"
        summary_sheet.append(["Field", "Value"])
        summary_sheet.append(["Trip ID", payload.get("tripId")])
        summary_sheet.append(["Report Type", payload.get("reportType")])
        summary_sheet.append(["Generated At (UTC)", datetime.now(timezone.utc).isoformat()])
        summary_sheet.append(["Blocked By Unresolved Disputes", payload.get("blockedByUnresolvedDisputes")])
        summary_sheet.append(["Unresolved Dispute Count", payload.get("unresolvedDisputeCount")])
        summary_sheet.append(["Generated By Member", payload.get("generatedByMemberId")])
        summary_sheet["A1"].font = Font(bold=True)
        summary_sheet["B1"].font = Font(bold=True)
        summary_sheet.column_dimensions["A"].width = 34
        summary_sheet.column_dimensions["B"].width = 44

        transfers_sheet = workbook.create_sheet("Who Owes Whom")
        transfers_sheet.append(["From Member", "To Member", "Amount"])
        transfers_sheet["A1"].font = Font(bold=True)
        transfers_sheet["B1"].font = Font(bold=True)
        transfers_sheet["C1"].font = Font(bold=True)
        for row in payload.get("whoOwesWhom", []):
            transfers_sheet.append([row.get("fromMemberId"), row.get("toMemberId"), float(row.get("amount") or 0)])
        transfers_sheet.column_dimensions["A"].width = 36
        transfers_sheet.column_dimensions["B"].width = 36
        transfers_sheet.column_dimensions["C"].width = 16

        balances_sheet = workbook.create_sheet("Member Balances")
        balances_sheet.append(["Member", "Net Balance"])
        balances_sheet["A1"].font = Font(bold=True)
        balances_sheet["B1"].font = Font(bold=True)
        for member_id, amount in payload.get("memberBalances", {}).items():
            balances_sheet.append([member_id, float(amount or 0)])
        balances_sheet.column_dimensions["A"].width = 36
        balances_sheet.column_dimensions["B"].width = 18

        workbook.save(file_path)

    def _write_pdf(self, *, file_path: Path, payload: dict) -> None:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

        doc = SimpleDocTemplate(
            str(file_path),
            pagesize=A4,
            rightMargin=16 * mm,
            leftMargin=16 * mm,
            topMargin=14 * mm,
            bottomMargin=14 * mm,
        )
        styles = getSampleStyleSheet()
        story: list[Any] = []

        story.append(Paragraph("TripWise Settlement Report", styles["Title"]))
        story.append(Spacer(1, 6))
        story.append(Paragraph(f"Trip ID: {payload.get('tripId')}", styles["BodyText"]))
        story.append(Paragraph(f"Report Type: {payload.get('reportType')}", styles["BodyText"]))
        story.append(Paragraph(f"Generated By: {payload.get('generatedByMemberId')}", styles["BodyText"]))
        story.append(Paragraph(f"Blocked By Disputes: {payload.get('blockedByUnresolvedDisputes')}", styles["BodyText"]))
        story.append(Paragraph(f"Unresolved Disputes: {payload.get('unresolvedDisputeCount')}", styles["BodyText"]))
        story.append(Spacer(1, 10))

        transfer_rows = [["From Member", "To Member", "Amount"]]
        for row in payload.get("whoOwesWhom", []):
            transfer_rows.append([str(row.get("fromMemberId") or ""), str(row.get("toMemberId") or ""), f"{float(row.get('amount') or 0):.2f}"])
        if len(transfer_rows) == 1:
            transfer_rows.append(["-", "-", "No outstanding transfers"])

        transfer_table = Table(transfer_rows, colWidths=[70 * mm, 70 * mm, 30 * mm])
        transfer_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F0F4F8")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0F1A24")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#C9D4DE")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#FAFCFE")]),
                ]
            )
        )
        story.append(transfer_table)
        story.append(Spacer(1, 10))

        balance_rows = [["Member", "Net Balance"]]
        for member_id, amount in payload.get("memberBalances", {}).items():
            balance_rows.append([str(member_id), f"{float(amount or 0):.2f}"])
        if len(balance_rows) == 1:
            balance_rows.append(["-", "0.00"])

        balance_table = Table(balance_rows, colWidths=[140 * mm, 30 * mm])
        balance_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F0F4F8")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#C9D4DE")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#FAFCFE")]),
                ]
            )
        )
        story.append(balance_table)
        doc.build(story)

    def _csv_value(self, value: Any) -> str:
        text = str(value)
        if any(ch in text for ch in [",", '"', "\n"]):
            return '"' + text.replace('"', '""') + '"'
        return text


report_artifact_service = ReportArtifactService()
